# Generated by Django 4.2.2 on 2023-07-28 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginApp', '0002_alter_customersignup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_names', models.CharField(max_length=250)),
                ('creation_dates', models.DateField(auto_now_add=True)),
                ('update_dates', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='loanTransactions',
            fields=[
                ('transactions', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payments', models.PositiveIntegerField(default=0)),
                ('payment_dates', models.DateField(auto_now_add=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customers', to='LoginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_dates', models.DateField(auto_now=True)),
                ('status_dates', models.DateField(blank=True, default=None, max_length=150, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('reason_for_rejection_approval', models.TextField()),
                ('amounts', models.PositiveIntegerField(default=0)),
                ('amount_approved', models.PositiveIntegerField(default=0)),
                ('categorys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.loancategorys')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customers', to='LoginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loans', models.PositiveIntegerField(default=0)),
                ('payable_loans', models.PositiveIntegerField(default=0)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_users', to='LoginApp.customersignup')),
            ],
        ),
    ]
