# Generated by Django 4.2.2 on 2023-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='phone',
            field=models.TextField(blank=True, default='0773323264', max_length=250),
        ),
    ]
