# Generated by Django 4.2.2 on 2023-10-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_alter_customersignup_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersignup',
            old_name='user',
            new_name='username',
        ),
    ]
